// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.887
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func UserForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"es\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Formulario Usuario</title><link href=\"../src/output.css\" rel=\"stylesheet\"></head><body class=\"bg-gray-100 p-6\"><form method=\"POST\" action=\"/users\" class=\"max-w-md mx-auto p-6 bg-white rounded-xl shadow-md space-y-4\"><h2 class=\"text-2xl font-bold mb-4\">Crear Usuario</h2><div><label for=\"username\" class=\"block text-sm font-medium text-gray-700\">Username</label> <input type=\"text\" id=\"username\" name=\"username\" maxlength=\"30\" required class=\"mt-1 block w-full border border-gray-300 rounded-md p-2\"></div><div><label for=\"email\" class=\"block text-sm font-medium text-gray-700\">Email</label> <input type=\"email\" id=\"email\" name=\"email\" required class=\"mt-1 block w-full border border-gray-300 rounded-md p-2\"></div><div><label for=\"password\" class=\"block text-sm font-medium text-gray-700\">Password</label> <input type=\"password\" id=\"password\" name=\"password\" required class=\"mt-1 block w-full border border-gray-300 rounded-md p-2\"></div><div><label for=\"name\" class=\"block text-sm font-medium text-gray-700\">Nombre</label> <input type=\"text\" id=\"name\" name=\"name\" class=\"mt-1 block w-full border border-gray-300 rounded-md p-2\"></div><div><label for=\"lastname\" class=\"block text-sm font-medium text-gray-700\">Apellido</label> <input type=\"text\" id=\"lastname\" name=\"lastname\" class=\"mt-1 block w-full border border-gray-300 rounded-md p-2\"></div><div class=\"flex justify-end\"><button type=\"submit\" class=\"bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700\">Guardar</button></div></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
